# Generated by Django 4.0.2 on 2022-02-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simbapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_name', models.CharField(max_length=50)),
                ('dog_age', models.IntegerField()),
                ('dog_owner', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Dog Info',
            },
        ),
    ]
